repos:
  - repo: https://github.com/omnilib/ufmt
    rev: v2.7.0
    hooks:
      - id: ufmt
        additional_dependencies:
          - black == 22.6
          - usort == 1.0.8

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-docstring-first
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

exclude: migrations/
