version: "3.8"
name: app_name_project

services:

  backend:
    ports:
      - 8000:8000
    build:
      context: .
    entrypoint: ["/app/docker-entrypoint.sh"]
#    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --log-level=info
    container_name: app_name_project-backend
    env_file:
      - ./vault/env
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://backend:8000/healthcheck || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15.3
    container_name: app_name_db
    env_file:
      - ./vault/env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d test_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data:
